version: '2'
services:
  namenode:
    image: bde2020/hadoop-namenode:1.0.0
    hostname: namenode
    container_name: namenode
    domainname: hadoop
    volumes:
      - /openblockchain/hadoop/data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - "50070:50070"
      - "8020:8020"

  datanode1:
    image: bde2020/hadoop-datanode:1.0.0
    hostname: datanode1
    container_name: datanode1
    domainname: hadoop
    volumes:
      - /openblockchain/hadoop/data/datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

#  datanode2:
#    image: bde2020/hadoop-datanode:1.0.0
#    hostname: datanode2
#    container_name: datanode2
#    domainname: hadoop
#    volumes:
#      - /openblockchain/hadoop/data/datanode2:/hadoop/dfs/data
#    env_file:
#      - ./hadoop.env

  spark-master:
    image: aluxian/hadoop-spark-master
#    build: '../../docker-spark/spark-master'
    hostname: spark-master
    container_name: spark-master
    domainname: hadoop
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - SPARK_CONF_spark_eventLog_enabled=true
      - SPARK_CONF_spark_eventLog_dir=hdfs://namenode:8020/spark-logs
      - SPARK_CONF_spark_history_fs_logDirectory=hdfs://namenode:8020/spark-logs
    env_file:
      - ./hadoop.env
    volumes:
      - /openblockchain/jars:/jars
    ports:
        - "6066:6066"
        - "7077:7077"
        - "8080:8080"

  spark-worker:
    image: aluxian/hadoop-spark-worker
#    build: '../../docker-spark/spark-worker'
    hostname: spark-worker
    domainname: hadoop
    extra_hosts:
      - 'spark-master.hadoop:172.18.0.9'
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - SPARK_CONF_spark_eventLog_enabled=true
      - SPARK_CONF_spark_eventLog_dir=hdfs://namenode:8020/spark-logs
      - SPARK_CONF_spark_history_fs_logDirectory=hdfs://namenode:8020/spark-logs
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8081:8081"
      - "4040:4040"
    volumes:
       - /openblockchain/jars:/jars
    env_file:
      - ./hadoop.env

  hue:
    image: bde2020/hdfs-filebrowser:3.9
    hostname: hdfsfb
    container_name: hdfsfb
    domainname: hadoop
    environment:
      - NAMENODE_HOST=namenode
    ports:
      - "8088:8088"

networks:
  default:
    external:
      name: openblockchain
